language: node_js
node_js:
  - 4.5
sudo: false
cache:
  directories:
    - node_modules
after_success: npm run coverage
deploy:
  provider: npm
  api_key:
    secure: FroI5X5Cd2YjsCWSThQZWVqtHfv740ow9btBBEyzs7Zq77qdoB0/MHJkErqRhxpJ+Shj4nWuTMmeGcmeSKARGB67e5icpEcY/9wyCLDFwY96gEdWYdYosQ4Eq1ywNP70Uh+n3qoHFM9zynfGr+StESOtSxvZGKrICySS64SD9XZdTY84H6VZdApxpjbaxpYSzCFopdmh0hmhFfne6//zuM1BCFURstvfYQaaL1qkW4DE3Hq9W4HUeODr49j8rblyxeQIJBSKPfR7lxxmLH2fLkFU0OY0D76w/bW0QzztseAu6Dvi3oqjuFcgvDGB+S8oiNZyppaBMFxE1bxFmvKYLfuTsUOwk/430baF3c7GlUJjdhiRpWvhJwWEgF099Ssu55fepNFrU5rt9mzB/ZtR5WIesZx+TjvffY4PRuj5juyzXEKWMiYT/haEH4ovMNsL/GByn1RewNzL0vkhTZ3EUNc1+w3R0prEAuKYUuNqfUqn/LcmpfLYW+g6a9Ce6mWpteRRC14Z6i2oIAjXapAlvi3IWzXQmXwOJpW30ny6BhDH2+RiTL49KMImvNwmohd/DWALWHOUYfuJrLNpluKPuNWpGzzNXTk/bTdpiPdCCGvZd+QOHnY+rIezzu9iAwlDJO0kGIO36fr8QGd9DfIK33jNQUypNGbmeexGKa0TM5o=
  on:
    tags: true
